Feat: Typography 컴포넌트
santa-close/santa-close-client pull request #118
Opened 2022-06-06 09:24 UTC by EUNYUSEO

## Description

* Typography 컴포넌트

## Help Wanted 👀

* 

## Related Issues

* resolve #108 

## Checklist ✋

- [x] PR 타이틀을 `{PR type}: {PR title}`로 맞췄습니다. (type 예시: feat | fix | BREAKING CHANGE | chore | ci | docs | style | refactor | perf | test) (참고: [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/))
- [x] 모든 **변경점**들을 확인했으며 적절히 설명했습니다.
- [x] 빌드와 테스트가 정상적으로 수행됨을 확인했습니다. (`yarn build`, `yarn test`)
- [x] 깃헙 이슈를 연결하겠습니다. (커밋에 resolve #이슈넘버 적거나 PR생성 후 Linked Issue 추가)

2022-06-06 10:49 UTC, josworks27 commented on packages/santa_close_design-system/src/components/Typography/type.ts
> +  as?: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'p' | 'label'
as 위에 것들 외에도 더 받을 수 있어야 할 것 같습니다~!
https://chakra-ui.com/docs/components/typography/text#override-the-element

2022-06-06 10:50 UTC, josworks27 commented on packages/santa_close_design-system/src/components/Typography/type.ts
> +  children: string | number
복합적으로 스트링 만들 수 있게 ReactNode로 받는게 어떨까염?

2022-06-06 10:56 UTC, EUNYUSEO commented on packages/santa_close_design-system/src/components/Typography/type.ts
> +  as?: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'p' | 'label'
헉 그렇네요 더 많은 태그들이 있군요 🤔 url 참고해서 추가하겠습니다!

2022-06-06 11:05 UTC, EUNYUSEO commented on packages/santa_close_design-system/src/components/Typography/type.ts
> +  children: string | number
string과 number면 텍스트를 충분히 정의할 수 있다고 생각이 들었는데 복합적인 문자열을 만든다는 건 미처 생각하지 못한 부분이네요 🤔!! 잘 떠오르지가 않아서 그런데 호옥시 어떤 복합적인 문자열을 위해 ReactNode로 받는게 좋을지 알 수 있을까요?! 😇

2022-06-07 03:37 UTC, josworks27 commented on packages/santa_close_design-system/src/components/Typography/type.ts
> +  children: string | number
이렇게 컴포넌트가 포함된 스트링을 만들 때 문제가 되지 않을까 싶습니다.

```tsx
<Typography>
    foo<Typography color="main">bar</Typography>baz
</Typography>
```

2022-06-07 04:20 UTC, EUNYUSEO commented on packages/santa_close_design-system/src/components/Typography/type.ts
> +  children: string | number
아.. 그런 경우를 생각 못했네요. 또 하나 배워갑니다 😊🙏!! 예시 들어주셔서 감사합니다!

2022-06-07 10:30 UTC, EUNYUSEO commented on packages/santa_close_design-system/src/components/Typography/type.ts
> +  children: string | number
코드 수정했습니다 ㅎㅎ 확인 부탁드려요!! XD

2022-06-08 08:41 UTC, josworks27 requested changes

2022-06-08 08:41 UTC, josworks27 commented on .eslintrc.js
> +    'react/jsx-props-no-spreading': 'off',
이 옵션 관련한 린트 주석들 지워주실 수 있을까요?!
박스랑 버튼에 있어요🙏

2022-06-08 11:18 UTC, EUNYUSEO commented on packages/santa_close_map/src/App.tsx
>              {/* TODO: Typography component 구현 필요 */}
넵 지웠습니다~!

2022-06-08 11:19 UTC, EUNYUSEO commented on packages/santa_close_design-system/src/components/Typography/style.tsx
> +  fontFamily: '$untitled',
stitcges.config.ts 파일과 여기서 둘 다 수정했습니다~!!

2022-06-08 11:19 UTC, EUNYUSEO commented on .eslintrc.js
> +    'react/jsx-props-no-spreading': 'off',
넵 박스랑 버튼 컴포넌트에서 확인하고 각각 지웠습니다~!

2022-06-08 12:18 UTC, josworks27 approved these changes
LGTM👍 고생하셨습니다~! :)

2022-06-08 12:19 UTC, merged